language: node_js
node_js:
- 6
- 10
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
- yarn build-storybook
deploy:
  provider: firebase
  skip_cleanup: true
after_success:
- npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: dzN2hP1iCQKb6AoBOtq5z5BhZ0tv5pnpUrx9rj5J9jMZyd5uqmqI1iDBUUYbr8iX3JFmZv9+YmAgf8AOze7f9j2tPCVcV6WM3awSxhBT78696WcO3jiAk+8aiq408B8u1iJhiugHc7cXfv/WHjk+UhNPC6SbLPXmRYh9JfZETUSJiIn/E/k8WbRx50cJhac2rMTjju6oLYZ13aIhmU3zkUNQHuk0MPwYrQtiDG10Tj1mBPL6J310QQxoh2EPhKc46F2OuymsHhdU4hDvyH+4HRFi6dfUV+aXfGGDTs/3Vvs1S7S/9FjfpJ6JfoUtEU3+bUd7dMNfhxLAV0sjR+FSySuO48d/AwGYrbVJhfyRIdMsJ4I/YxGQJyJt8zyrvPgYiPQFo1YCxULUDc7tXSS7xzTQ4jj9mzF6hz1Z941qUK2gue8EOGNq0EnE3GwPqXejftyJYXb4Fed+w5y67Kb7K7J6ScKrVmYeY49IgRn6Azg19C8yZx3oAPlm5M9B1I+Lo9nqEx7Y+WLrvMjCI6KCP1Hhhv4SGX5vd423x4VOwFS6o3p9Kdy2+dlRvr89uJuobkoOg+6VBpjlIQI+YFMAyEsMyzMyarh2UjGYfVYiP0K7HPrVyPMUav+DXyrbI+p+ibD5B9Q6a5Qt57NeAX6ut9Pp775GHbj5RHU72riPls0=
